<?php

/**
 * @file
 * Module for listing existing employees and their task statistics.
 */
define('AI_EMPLOYEES_LIST_SECONDS_IN_MINUTE', '60');
define('AI_EMPLOYEES_LIST_SECONDS_IN_HOUR', '3600');
define('AI_EMPLOYEES_LIST_SECONDS_IN_DAY', '86400');

/**
 * @file
 * Convert DD:HH:MM:SS to seconds.
 */
function __dc_convert_to_seconds_DD_HH_MM_SS($time) {
  $time = explode(':', $time);
  return $time[0] * AI_EMPLOYEES_LIST_SECONDS_IN_DAY + $time[1] * AI_EMPLOYEES_LIST_SECONDS_IN_HOUR + $time[2] * AI_EMPLOYEES_LIST_SECONDS_IN_MINUTE + $time[3];
}
